import PALETTE from './palette'

const Color = {
  ...PALETTE,
  BACKGROUND_HEADER: PALETTE.LIGHT_GRAYISH_BLUE,
  BACKGROUND_MAIN: PALETTE.VERY_LIGHT_GRAY,
  BACKGROUND_FOOTER: PALETTE.LIGHT_GRAYISH_BLUE,
}

export default Color
